let data=[
    {
        "id":0,
        "image":"./images/f1.jpg",
        "title":"product title",
        "description":"Lorem ipsum dolor sit amet consectetur, adipisicing elit Qui ipsam.",
        "price":40,
    },
    {
        "id":1,
        "image":"./images/f2.jpg",
        "title":"product title",
        "description":"Lorem ipsum dolor sit amet consectetur, adipisicing elit Qui ipsam.",
        "price":54,
    },
    {
        "id":2,
        "image":"./images/f3.jpg",
        "title":"product title",
        "description":"Lorem ipsum dolor sit amet consectetur, adipisicing elit Qui ipsam.",
        "price":65,
    },
    {
        "id":3,
        "image":"./images/f4.jpg",
        "title":"product title",
        "description":"Lorem ipsum dolor sit amet consectetur, adipisicing elit Qui ipsam.",
        "price":45,
    },
    {
        "id":4,
        "image":"./images/f5.jpg",
        "title":"product title",
        "description":"Lorem ipsum dolor sit amet consectetur, adipisicing elit Qui ipsam.",
        "price":74,
    },
    {
        "id":5,
        "image":"./images/f6.jpg",
        "title":"product title",
        "description":"Lorem ipsum dolor sit amet consectetur, adipisicing elit Qui ipsam.",
        "price":98,
    },
    {
        "id":6,
        "image":"./images/n8.jpg",
        "title":"product title",
        "description":"Lorem ipsum dolor sit amet consectetur, adipisicing elit Qui ipsam.",
        "price":62,
    },
    {
        "id":7,
        "image":"./images/n4.jpg",
        "title":"product title",
        "description":"Lorem ipsum dolor sit amet consectetur, adipisicing elit Qui ipsam.",
        "price":64,
    },
    {
        "id":8,
        "image":"./images/n1.jpg",
        "title":"product title",
        "description":"Lorem ipsum dolor sit amet consectetur, adipisicing elit Qui ipsam.",
        "price":125,
    },
    {
        "id":9,
        "image":"./images/n5.jpg",
        "title":"product title",
        "description":"Lorem ipsum dolor sit amet consectetur, adipisicing elit Qui ipsam.",
        "price":102,
    },
    {
        "id":10,
        "image":"./images/n3.jpg",
        "title":"product title",
        "description":"Lorem ipsum dolor sit amet consectetur, adipisicing elit Qui ipsam.",
        "price":68,
    },
    {
        "id":11,
        "image":"./images/n2.jpg",
        "title":"product title",
        "description":"Lorem ipsum dolor sit amet consectetur, adipisicing elit Qui ipsam.",
        "price":74,
    },
        
]